- name: Download and install PHP
  when: ansible_hostname == "app"
  yum:
    name:
      - epel-release
      - yum-utils
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: installed
- name: Enable PHP 7.3 Remi repo
  when: ansible_hostname == "app"
  yum:
    enablerepo: "remi,remi-php73"
    name:
      - php
      - php-common
      - php-opcache
      - php-mcrypt
      - php-cli
      - php-gd
      - php-curl
      - php-mysql
      - mysql
      - mariadb
      - mariadb-server
      - php-xml
      - php-mbstring
    state: latest
  
  