- name: Create database
  when: ansible_hostname == "mysql"
  mysql_db:
    login_user: 'root'
    login_password: '{{ mysqlrootpassword }}'
    name: "{{ dbname }}"
    state: present
- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  when: ansible_hostname == "mysql"
  mysql_user:
    login_user: 'root'
    login_password: '{{ mysqlrootpassword }}'
    name: "{{ db_username }}"
    password: "{{ dbuser_password }}"
    priv: 'wordpress.*:ALL,GRANT'
    state: present
    host: "{{ appip }}"