- name: Install  mariadb
  when: ansible_hostname == "mysql"
  yum: 
    name: 
      - mariadb
      - mariadb-server
    state: latest
- name: Start and enable Mariadb
  when: ansible_hostname == "mysql"
  systemd:
    state: started
    enabled: yes
    name: mariadb